=== stn1slv/meetup-schema-registry/schemas/PurchaseOrderV1.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://example.com/product.schema.json",
    "title": "PurchaseOrder",
    "description": "Purchase order",
    "type": "object",
    "properties": {
        "name": {
            "type": "string",
            "maxLength": 512
        },
        "sku": {
            "type": "string"
        },
        "price": {
            "type": "number",
            "minimum": 0
        },
        "orderDate": {
            "type": "string",
            "format": "date"
        },
        "shipTo": {
            "type": "object",
            "properties": {
                "country": {
                    "type": "string",
                    "default": "US",
                    "minLength": 2,
                    "maxLength": 2
                },
                "state": {
                    "type": "string",
                    "minLength": 2,
                    "maxLength": 2
                },
                "city": {
                    "type": "string"
                },
                "street": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "zip": {
                    "type": "string"
                }
            }
        },
        "billTo": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "address": {
                    "type": "string"
                },
                "city": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                },
                "zip": {
                    "type": "string"
                }
            }
        }
    },
    "required": [
        "name",
        "sku",
        "price",
        "orderDate",
        "shipTo"
    ]
}

=== stn1slv/meetup-schema-registry/examples/purchaseOrderV1_Alice.json
{
    "name": "Alice Brown",
    "sku": "54321",
    "price": 199.95,
    "orderDate": "2020-10-10",
    "shipTo": {
        "name": "Bob Brown",
        "address": "456 Oak Lane",
        "city": "Pretendville",
        "state": "HI",
        "zip": "98999"
    },
    "billTo": {
        "name": "Alice Brown",
        "address": "456 Oak Lane",
        "city": "Pretendville",
        "state": "HI",
        "zip": "98999"
    }
}
